import streamlit as st
import requests
import os
import json
from dotenv import load_dotenv

# CONFIGURATION 
load_dotenv()
CRYPTO_WEBHOOK = os.getenv("N8N_CRYPTO_WEBHOOK_URL")

st.set_page_config(page_title="InsightFlow Crypto", page_icon="🪙", layout="wide") 

# CSS Styling for Metrics 
st.markdown("""
<style>
    .stMetric {
        background-color: #1E1E1E;
        padding: 15px;
        border-radius: 10px;
        border: 1px solid #333;
    }
</style>
""", unsafe_allow_html=True)

# BACKEND FUNCTION 
def get_crypto_market_scan():
    try:
        response = requests.post(CRYPTO_WEBHOOK, json={"query": "scan"})
        if response.status_code == 200:
            return response.json()
        else:
            return {"error": f"Status: {response.status_code}"}
    except Exception as e:
        return {"error": str(e)}

# MAIN DASHBOARD
st.title("🪙 InsightFlow: Crypto Intelligence")
st.markdown("**Senior Analyst Dashboard: Phase 0 & 1 (Quant Scan)**")

if st.button("🔄 Scan Market Regime (Live)"):
    with st.spinner("Connecting to Bloomberg Terminal... (Collecting Quant Data)"):
        data = get_crypto_market_scan()
    
    if "error" in data:
        st.error(f"System Failure: {data['error']}")
    else:
        st.subheader("0️⃣ Pre-Market Context")
        
        # Baris 1: Metrik Utama 
        col1, col2, col3 = st.columns(3)
        
        with col1:
            st.metric("Market Regime", data.get('regime', 'Unknown'))
        
        with col2:
            sent_label = data.get('sentiment_label', 'Neutral')
            sent_val = data.get('sentiment_score', 50)
            delta_color = "normal"
            if "Greed" in sent_label: delta_color = "inverse" 
            
            st.metric("Sentiment (Fear & Greed)", f"{sent_val}/100", sent_label)

        with col3:
            st.metric("BTC Dominance Trend", data.get('btc_dom_trend', '-'))

        # Baris 2: Analisis Naratif Singkat
        with st.container(border=True):
            st.markdown("### 📝 Analyst Insight")
            st.write(data.get('analysis_summary', 'No analysis available.'))
            st.caption("Generated by InsightFlow Crypto Engine (Llama 3.3)")

# SIDEBAR for development phase info 
with st.sidebar:
    st.info("Current Module: **Quant Scan**")
    st.markdown("""
    **Workflow Status:**
    - ✅ Phase 0: Market Context
    - 🚧 Phase 1: Capital Rotation
    """)