import streamlit as st
import requests
import os
import json
from dotenv import load_dotenv

# CONFIGURATION 

load_dotenv()
CRYPTO_WEBHOOK = os.getenv("N8N_CRYPTO_WEBHOOK_URL")

st.set_page_config(page_title="InsightFlow Crypto", page_icon="🪙", layout="wide") 

# CSS Styling for Metrics 
st.markdown("""
<style>
    .stMetric {
        background-color: #1E1E1E;
        padding: 15px;
        border-radius: 10px;
        border: 1px solid #333;
    }
</style>
""", unsafe_allow_html=True)

# BACKEND FUNCTION 
def call_n8n(action_input):
    """
    Fungsi fleksibel untuk memanggil n8n.
    - Jika input string (misal: 'quant'), otomatis dibungkus jadi {"action": "quant"}
    - Jika input dict (misal: {"action": "deep_dive", "query": "..."}), dikirim langsung.
    """
    # Cek Tipe Data 
    if isinstance(action_input, dict):
        payload = action_input  
    else:
        payload = {"action": action_input} 
    try:
        response = requests.post(CRYPTO_WEBHOOK, json=payload)
        
        if response.status_code == 200:
            return response.json()
        else:
            return {"error": f"Status: {response.status_code}"}
    except Exception as e:
        return {"error": f"Connection Error: {str(e)}"}

st.title("🪙 InsightFlow: Crypto Intelligence")
# Navigasi Tab
tab1, tab2, tab3 = st.tabs(["0️⃣ Quant Scan (Context)", "2️⃣ Narrative Radar (Trends)", "3️⃣ Deep Dive Analyzer"])

    # TAB 1: Quant Scan 
with tab1:
    st.markdown("### Pre-Market Alignment")
    if st.button("🔄 Scan Market Regime", key="btn_quant"):
        with st.spinner("Connecting to Bloomberg Terminal..."):
            data = call_n8n("quant") 
        
        if "error" in data:
            st.error(data['error'])
        else:
                    col1, col2, col3 = st.columns(3)
        
        with col1:
            st.metric("Market Regime", data.get('regime', 'Unknown'))
        
        with col2:
            sent_label = data.get('sentiment_label',"-")
            sent_val = data.get('sentiment_score')
            delta_color = "normal"
            if "Greed" in sent_label: delta_color = "inverse" 
            
            st.metric("Sentiment (Fear & Greed)", f"{sent_val}/100", sent_label)

        with col3:
            st.metric("BTC Dominance Trend", data.get('btc_dominance_trend', '-'))

        # Analisis Naratif Singkat
        with st.container(border=True):
            st.markdown("### 📝 Analyst Insight")
            st.write(data.get('analysis_summary', 'No analysis available.'))
            st.caption("Generated by InsightFlow Crypto Engine (Llama 3.3)")

# TAB 2: Narrative Radar 
with tab2:
    st.markdown("### 📡 Narrative & Trend Intelligence")
    st.caption("Mendeteksi narasi sebelum terefleksi pada harga (Phase 2 Workflow).")
    
    if st.button("SEARCH NARRATIVES 🕵️", key="btn_narrative"):
        with st.spinner("Scraping social signals & news..."):
            data = call_n8n("narrative") 
            
        if "error" in data:
            st.error(data['error'])
        else:
            # Summary Section
            st.success(data.get('summary_insight', 'Scan Complete'))
            
            # Narrative Cards Loop
            narratives = data.get('narratives', [])
            
            if not narratives:
                st.warning("No specific narratives detected.")
            else:
                # Membuat Grid Layout
                cols = st.columns(3)
                for idx, item in enumerate(narratives):
                    with cols[idx % 3]: # Membagi ke kolom secara merata
                        with st.container(border=True):
                            st.subheader(item.get('name', 'Unknown'))
                            
                            velocity = item.get('velocity', '-')
                            if "Exploding" in velocity: st.markdown("🔥 **Exploding**")
                            elif "Rising" in velocity: st.markdown("📈 **Rising**")
                            else: st.markdown(f"➡️ {velocity}")
                            
                            st.progress(90 if 'Hype' in item.get('maturity','') else 40)
                            st.caption(f"Phase: {item.get('maturity', '-')}")
                            st.write(item.get('insight', '-'))
# TAB 3: DEEP DIVE 
with tab3:
    st.markdown("### 🔍 Fundamental Deep Dive")
    st.caption("Audit fundamental proyek: Tokenomics, Business Model, & Competitive Moat.")

    coin_query = st.text_input("Masukkan nama proyek/koin:", placeholder="Contoh: Solana, Ondo Finance, Pendle...")

    if st.button("ANALYZE PROJECT 🧪", key="btn_deep_dive"):
        if not coin_query:
            st.warning("Mohon isi nama proyek.")
        else:
            with st.spinner(f"Melakukan audit fundamental untuk {coin_query}..."):
                
                payload = {
                    "action": "deep_dive", 
                    "query": coin_query
                }

                data = call_n8n(payload)
                
                # UI
                if "error" in data:
                    st.error(data['error'])
                else:
                    # Header Laporan
                    project_name = data.get('project_name', coin_query)
                    st.subheader(f"📑 Laporan Audit: {project_name}")
                    
                    # Score Gauge & Verdict
                    score = data.get('score', 0)
                    col_score, col_verdict = st.columns([1, 2])
                    
                    with col_score:
                        st.metric("Fundamental Score", f"{score}/10")
                        st.progress(score / 10)
                    
                    with col_verdict:
                        st.info(f"**💡 Verdict:** {data.get('verdict', '-')}")

                    # Pros & Cons Section
                    c1, c2 = st.columns(2)
                    with c1:
                        st.success("✅ **Kekuatan (Pros)**")
                        pros = data.get('pros', [])
                        if pros:
                            for pro in pros:
                                st.write(f"- {pro}")
                        else:
                            st.write("- Data tidak ditemukan")

                    with c2:
                        st.error("⚠️ **Risiko (Cons)**")
                        cons = data.get('cons', [])
                        if cons:
                            for con in cons:
                                st.write(f"- {con}")
                        else:
                            st.write("- Data tidak ditemukan")

# SIDEBAR for development phase info 
with st.sidebar:
    st.info("Current Phase: **Phase 3 - Deep Dive Analyzer**")
    st.markdown("""
    **Workflow Status:**
    - ✅ Phase 0: Market Context
    - 🚧 Phase 1: Capital Rotation
    - ⏳ Phase 2: Narrative Radar
    - 🆕 Phase 3: Deep Dive Analyzer
    """)
    