import streamlit as st
import requests
import os
import json
from dotenv import load_dotenv

# --- 1. CONFIGURATION & SETUP ---
# Memuat variabel environment dari file .env
load_dotenv()

# Mengambil URL n8n. Jika tidak ada, aplikasi akan stop demi keamanan.
N8N_WEBHOOK_URL = os.getenv("N8N_WEBHOOK_URL")
if not N8N_WEBHOOK_URL:
    st.error("⚠️ Error: N8N_WEBHOOK_URL belum disetting di file .env")
    st.stop()

# Konfigurasi Halaman Streamlit (Judul Tab, Ikon, Layout)
st.set_page_config(
    page_title="InsightFlow AI",
    page_icon="🕵️",
    layout="centered"
)

# --- 2. BACKEND LOGIC (HELPER FUNCTION) ---
def get_ai_insight(topic):
    """
    Fungsi untuk mengirim request ke n8n dan menangani error koneksi.
    """
    try:
        payload = {"query": topic}
        # Mengirim POST request ke n8n
        response = requests.post(N8N_WEBHOOK_URL, json=payload)
        
        # Cek apakah status code 200 (OK)
        if response.status_code == 200:
            return response.json()
        else:
            return {"error": f"Gagal terhubung ke AI. Status Code: {response.status_code}"}
            
    except requests.exceptions.ConnectionError:
        return {"error": "Tidak bisa menghubungi server n8n. Pastikan n8n berjalan!"}
    except Exception as e:
        return {"error": f"Terjadi kesalahan teknis: {str(e)}"}

# --- 3. FRONTEND USER INTERFACE ---

# Header Section
st.title("🕵️ InsightFlow")
st.markdown("""
    **AI-Powered Competitor & Market Intelligence Agent.** Masukkan topik, kompetitor, atau tren pasar, dan biarkan AI melakukan riset mendalam untuk Anda.
""")

st.divider() # Garis pemisah visual

# Input Section
with st.form("research_form"):
    topic_input = st.text_input(
        "Apa yang ingin Anda riset hari ini?",
        placeholder="Contoh: Strategi Gojek vs Grab 2025, Tren AI di Pertanian..."
    )
    
    # Tombol Submit
    submitted = st.form_submit_button("Mulai Analisis 🚀")

# Result Section
if submitted:
    if not topic_input:
        st.warning("Mohon isi topik terlebih dahulu.")
    else:
        # Menampilkan indikator loading (UX yang baik)
        with st.spinner('Sedang mencari data di internet, membaca artikel, dan menulis laporan...'):
            # Memanggil fungsi backend
            data = get_ai_insight(topic_input)

        # Menampilkan Hasil
        if "error" in data:
            st.error(data["error"])
        elif "result" in data:
            st.success("Analisis Selesai!")
            
            # Container hasil dengan formatting Markdown
            with st.container(border=True):
                st.markdown(data["result"])
                
                # Footer kecil
                st.caption(f"🤖 Generated by Llama 3 via Groq & n8n. Topic: {topic_input}")
        else:
            # Fallback jika format JSON aneh
            st.error("Format respon tidak dikenali. Cek output n8n.")
            st.json(data)

# Sidebar (Untuk kesan profesional/branding portofolio)
with st.sidebar:
    st.header("Tentang Proyek")
    st.info("""
    Proyek ini mendemonstrasikan integrasi **End-to-End AI Engineering**:
    - **Frontend:** Streamlit (Python)
    - **Orchestration:** n8n Workflow
    - **Search:** Google Serper API
    - **LLM:** Llama 3-70B (Groq)
    """)
    st.markdown("---")
    st.caption("Developed for AI Portfolio")